"""e-Gazette adapter (Docs/APIs.md §4).

Live target: egazette.gov.in — the notification a s.11/s.19 or 3A/3D event has to
point at.

The mock is a local cache: the synthetic gazette PDFs in `api/seed/demo_uploads`,
generated by `seed/make_gazette_pdfs.py` to the real layout and phrasing. Their
metadata is not re-derived here — `app.domain.documents.extraction` already reads a
gazette dateline and S.O. number out of these exact files for the upload path, so
`search()` calls it rather than growing a second, drifting parser.

Naming convention of the cache (set by `make_gazette_pdfs.make_all`):
`gazette_<SECTION>_<case no with '/' replaced by '-'>.pdf`, e.g.
`gazette_3D_LAQ-SEO-2025-01.pdf` -> section 3D, case LAQ/SEO/2025/01.
"""

from __future__ import annotations

import hashlib
import logging
from datetime import date
from pathlib import Path

from app.domain.integrations.base import BaseAdapter, register

log = logging.getLogger(__name__)

# api/seed/demo_uploads — app/__init__.py sits at api/app/__init__.py.
CACHE_DIR = Path(__file__).resolve().parents[3] / "seed" / "demo_uploads"

# Which Act a section number belongs to. Sections outside the table are reported
# with `statute: None` rather than guessed at.
STATUTE_FOR_SECTION = {
    "3A": "NH_ACT_1956",
    "3D": "NH_ACT_1956",
    "3G": "NH_ACT_1956",
    "S11": "RFCTLARR_2013",
    "S19": "RFCTLARR_2013",
    "S23": "RFCTLARR_2013",
}

_meta_cache: dict[tuple, dict] = {}


def cache_dir() -> Path:
    return CACHE_DIR


def _section_label(section: str) -> str:
    """`3D` -> `s.3D`; `S11` -> `s.11` — the way the Act is cited."""
    if section.upper().startswith("S") and section[1:].isdigit():
        return f"s.{section[1:]}"
    return f"s.{section}"


def _parse_date(value) -> date | None:
    if isinstance(value, date):
        return value
    try:
        return date.fromisoformat(str(value)[:10])
    except (ValueError, TypeError):
        return None


def _entry(path: Path) -> dict:
    """Metadata for one cached notification, memoised on (name, mtime, size)."""
    stat = path.stat()
    key = (path.name, stat.st_mtime_ns, stat.st_size)
    hit = _meta_cache.get(key)
    if hit is not None:
        return hit

    data = path.read_bytes()
    parts = path.stem.split("_")
    section = (parts[1] if len(parts) > 2 else "").upper()
    case_ref = parts[2].replace("-", "/") if len(parts) > 2 else None

    fields: dict = {}
    pages = None
    try:
        from app.domain.documents.extraction import extract_from_bytes

        result = extract_from_bytes(data)
        fields = result.fields or {}
        pages = result.pages or None
    except Exception:  # a cache file we cannot parse is still a cache file
        log.exception("gazette: could not read %s", path.name)

    entry = {
        "ref": path.stem,
        "filename": path.name,
        "section": section or (fields.get("section") or None),
        "section_label": _section_label(section) if section else None,
        "statute": STATUTE_FOR_SECTION.get(section) or fields.get("statute"),
        "case_ref": case_ref,
        "gazette_no": fields.get("gazette_no"),
        "published_on": fields.get("publication_date"),
        "state": fields.get("state"),
        "district": fields.get("district"),
        "total_area_ha": fields.get("total_area_ha"),
        "pages": pages,
        "size_bytes": stat.st_size,
        "sha256": hashlib.sha256(data).hexdigest(),
        "mime": "application/pdf",
        "source": "mock: local cache of synthetic e-Gazette PDFs",
    }
    _meta_cache[key] = entry
    return entry


def _entries() -> list[dict]:
    directory = cache_dir()
    if not directory.is_dir():
        return []
    return [_entry(p) for p in sorted(directory.glob("*.pdf"))]


class GazetteAdapter(BaseAdapter):
    name = "gazette"
    title = "e-Gazette notifications"
    mode = "mock"
    interface = "search(statute, section, from, to, state); fetch(ref)"
    real_target = "egazette.gov.in"
    mock_behaviour = "local cache of the synthetic gazette PDFs in seed/demo_uploads"

    # --- reads --------------------------------------------------------------------

    def search(
        self,
        statute: str | None = None,
        section: str | None = None,
        date_from=None,
        date_to=None,
        state: str | None = None,
    ) -> dict:
        """Notification refs matching the filters.

        Every scanned file lands in exactly one of `items` or `skipped`, and
        `skipped` names the filter that rejected it — a search that quietly drops a
        notification is worse than one that returns nothing.

        A file whose publication date could not be read is kept when a date window
        is given, and flagged `date_unknown`: excluding it would be a claim about a
        date we do not have.
        """
        lo, hi = _parse_date(date_from), _parse_date(date_to)
        items: list[dict] = []
        skipped: list[dict] = []
        for entry in _entries():
            reason = None
            if statute and (entry["statute"] or "").upper() != statute.strip().upper():
                reason = f"statute {entry['statute']} != {statute}"
            elif section and (entry["section"] or "").upper() != section.strip().upper():
                reason = f"section {entry['section']} != {section}"
            elif state and entry["state"] and (
                entry["state"].strip().lower() != state.strip().lower()
            ):
                reason = f"state {entry['state']} != {state}"
            else:
                if state and not entry["state"]:
                    # Returned, but flagged: we could not read a state out of this
                    # notification, so it is neither a match nor a rejection.
                    entry = {**entry, "state_unknown": True}
                published = _parse_date(entry["published_on"])
                if published is None and (lo or hi):
                    entry = {**entry, "date_unknown": True}
                elif published is not None:
                    if lo and published < lo:
                        reason = f"published {published.isoformat()} before {lo.isoformat()}"
                    elif hi and published > hi:
                        reason = f"published {published.isoformat()} after {hi.isoformat()}"
            if reason:
                skipped.append({"ref": entry["ref"], "reason": reason})
            else:
                items.append(entry)
        return {
            "items": items,
            "count": len(items),
            "skipped": skipped,
            "scanned": len(items) + len(skipped),
            "cache_dir": str(cache_dir()),
        }

    def fetch(self, ref: str) -> dict:
        """The cached PDF for `ref`: metadata plus the bytes under `content`.

        `content` is raw `bytes` — this is a Python-level adapter call, not a JSON
        response; the API surface that serves gazette PDFs is `/documents/{id}/file`.
        """
        wanted = (ref or "").strip()
        for entry in _entries():
            if entry["ref"].lower() == wanted.lower() or entry["filename"].lower() == wanted.lower():
                path = cache_dir() / entry["filename"]
                return {**entry, "found": True, "content": path.read_bytes()}
        return {
            "found": False,
            "ref": ref,
            "detail": "no notification with that ref in the local gazette cache",
        }

    def _test(self, db=None) -> dict:
        directory = cache_dir()
        if not directory.is_dir():
            return {"ok": False, "detail": f"gazette cache directory missing: {directory}"}
        entries = _entries()
        if not entries:
            return {"ok": False, "detail": f"gazette cache is empty: {directory}"}
        refs = [e["ref"] for e in entries]
        return {
            "ok": True,
            "detail": f"{len(entries)} cached notification(s): {', '.join(refs)}",
            "cache_dir": str(directory),
            "refs": refs,
        }


adapter = register(GazetteAdapter())
